core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('super/', include('superuser.urls')),
    path('users/', include('users.urls')),
    path('', include('admin_controle.urls')),
    path('instructor/', include('instructor.urls')),
    path('student/', include('student.urls')),
    path('Parent/', include('parent.url')),


    path('quiz-conf/', include('quiz_config.urls')),
    path('quiz/', include('quiz.urls')),



    path('api-user/', include('userapi.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('quizes/<schedule_name>/', views.quiz_view, name='quiz-view'),
    path('response/code/', views.check_quiz_code_response),

    path('questions/<quiz_id>/<schedule_name>/', views.question_view, name='questions'),


    path('get-quiz-degree/', views.get_quiz_degree),
    path('reports/<schedule_name>/', views.reports_views, name='quiz-reports-view'),

    path('report/<id>/<schedule_name>/', views.student_report, name='report-view'),
]

quiz/models.py
from django.db import models
from django.utils import timezone
import datetime

from users.models import InstructorAccount, StudentAccount






class Quiz(models.Model):
    DIFFICULT_CHOICES = [
        ('easy', 'easy'),
        ('medium', 'medium'),
        ('hard', 'hard'),
    ]
    schedule_name 		   = models.CharField(max_length=50)
    user                   = models.ForeignKey(InstructorAccount, on_delete=models.CASCADE)
    company_name           = models.CharField(max_length=50)
    name                   = models.CharField(max_length=50, unique=True)
    quiz_code              = models.CharField(max_length=50, unique=True)
    topic                  = models.CharField(max_length=50)
    number_of_chosen_questions = models.IntegerField()
    number_of_theory_questions = models.IntegerField()
    time                   = models.IntegerField(help_text='duration of the quiz in minutes.')
    required_score_to_pass = models.IntegerField(help_text='required score in %.')
    difficulty             = models.CharField(max_length=6, choices=DIFFICULT_CHOICES, default=DIFFICULT_CHOICES[0])
    start_quiz             = models.DateTimeField(null=True, blank=True)
    is_answered            = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}-{self.topic}'


class IntervalQuiz(models.Model):
    quiz         = models.OneToOneField(Quiz, on_delete=models.CASCADE)
    intervalTime = models.TimeField()


    def __str__(self):
        return f'{str(self.quiz)}'




class Question(models.Model):
    quiz               = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question           = models.CharField(max_length=50)
    is_theory_question = models.BooleanField(default=False)
    question_on        = models.DateTimeField(default=timezone.now)
    
    chose1             = models.CharField(max_length=200, null=True, blank=True)
    chose2             = models.CharField(max_length=200, null=True, blank=True)
    chose3             = models.CharField(max_length=200, null=True, blank=True)
    chose4             = models.CharField(max_length=200, null=True, blank=True)
    correct_chosen     = models.CharField(max_length=200, null=True, blank=True)
    
    theory_answer      = models.TextField(max_length=500, null=True, blank=True)
    answerd_on         = models.DateTimeField(default=datetime.datetime.utcnow() + datetime.timedelta(hours=2))
    
    def __str__(self):
        return f'{self.quiz}-{self.question}'

    @classmethod
    def chose_question(cls, quiz_id):
        question = Question.objects.filter(quiz=quiz_id, is_theory_question=False)
        if question.count() == 0:
            return False

        return list(question)

    @classmethod
    def theory_question(cls, quiz_id):
        question = Question.objects.filter(quiz=quiz_id, is_theory_question=True)
        if question.count() == 0:
            return False
        
        return list(question)



class ReportResult(models.Model):
    user = models.ForeignKey(StudentAccount, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    question = models.CharField(max_length=255)
    student_answer = models.CharField(max_length=255)
    correct_answer = models.TextField()

    is_true_answered = models.CharField(max_length=50, default='Correct answer')

    question_score = models.FloatField()
    on_date = models.DateTimeField(default=datetime.datetime.utcnow() + datetime.timedelta(hours=2))

    def __str__(self):
        return f'{self.user.id_college}-{self.quiz}'

class TotalDegree(models.Model):
    user = models.ForeignKey(StudentAccount, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    score_to_pass = models.CharField(max_length=50)
    total = models.FloatField()


    def __str__(self):
        return f'{self.user.id_college}-{self.quiz}'

quiz/views.py
import json, random

from users.models import InstructorAccount, StudentAccount
from .tasks import check_theory

from django.shortcuts import redirect, render, reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from .models import Quiz, Question, ReportResult


def quiz_view(request, schedule_name):
    if not request.user.is_authenticated:
        return redirect('home')

    if (
        not StudentAccount.objects.filter(username=request.user.username).exists() and
        not InstructorAccount.objects.filter(username=request.user.username).exists()
    ):
        return redirect('logout-view')

    context = {}
    context['Schedule_name'] = schedule_name
    expired_num_questions = []

    for quiz in Quiz.objects.filter(is_answered=False, schedule_name=schedule_name, company_name=request.user.company_name):
        theory_q = Question.objects.filter(quiz=quiz, is_theory_question=True)
        chosen_q = Question.objects.filter(quiz=quiz, is_theory_question=False)

        if not quiz.number_of_theory_questions <= theory_q.count() or not quiz.number_of_chosen_questions <= chosen_q.count():
            expired_num_questions.append(quiz.id)

        if quiz.number_of_chosen_questions + quiz.number_of_theory_questions == 0:
            expired_num_questions.append(quiz.id)

    all_quizes = Quiz.objects.exclude(id__in=expired_num_questions).filter(is_answered=False, schedule_name=schedule_name, company_name=request.user.company_name)
    context['all_quizes'] = all_quizes
    context['quiz_list'] = [int(q.id) for q in all_quizes]

    if StudentAccount.objects.filter(username=request.user.username).exists():
        return render(request, 'quiz/quiz_view_st.html', context=context)

    
    

def check_quiz_code_response(request):
    quiz_code = request.GET.get('quiz_code')
    quiz_id   = request.GET.get('quiz_id')

    quiz = Quiz.objects.get(id=quiz_id)
    if quiz.quiz_code == quiz_code:
        return JsonResponse({'true': True})
    else:
        return JsonResponse({'flier': 'Failure quiz code!'})

def question_view(request, *args, **kwargs):
    quiz_id = kwargs['quiz_id']


    context = {}
    quiz_name = Quiz.objects.get(id=quiz_id)

    if ReportResult.objects.filter(user=request.user, quiz=quiz_name).exists():
        return redirect(reverse('quiz-view', kwargs={'schedule_name': kwargs['schedule_name']}))

    context['quiz_name'] = quiz_name.name
    context['quiz_id'] = quiz_id

    theory_question = Question.theory_question(int(quiz_id))
    chose_question  = Question.chose_question(int(quiz_id))

    if theory_question and chose_question:

        random_theory = random.sample(theory_question, k=int(quiz_name.number_of_theory_questions))
        random_chose  = random.sample(chose_question, k=int(quiz_name.number_of_chosen_questions))

        for q in random_chose: random_theory.append(q)
        context['question'] = random_theory
        

    elif theory_question and not chose_question:

        random_theory = random.sample(theory_question, k=int(quiz_name.number_of_theory_questions))
        context['question'] = random_theory

    elif chose_question and not theory_question:

        random_chose = random.sample(chose_question, k=int(quiz_name.number_of_chosen_questions))
        context['question'] = random_chose
    
    return render(request, 'quiz/question_view.html', context=context)

@csrf_exempt
def get_quiz_degree(request):
    data = json.loads(request.POST.get('data_json'))
    quiz_id = request.POST.get('quiz_id')

    dd = {'1': {'answer': 'not_answered', 'is_theory': 'True'},
          '2': {'answer': 'not_answered', 'is_theory': 'True'},
          '5': {'answer': 'not_answered', 'is_theory': 'False'},
          '6': {'answer': 'not_answered', 'is_theory': 'False'},
          '7': {'answer': 'not_answered', 'is_theory': 'False'}
          }

    check_theory.delay(data, request.user, quiz_id)





    return JsonResponse(request.POST.get('data_json'), safe=False)



# student reports #
def reports_views(request, schedule_name):


    report_quiz = ReportResult.objects.filter(user=request.user)
    list_quiz = []
    for x in report_quiz:
        list_quiz.append(x.quiz.id)

    my_quizes = Quiz.objects.filter(id__in=list_quiz, schedule_name=schedule_name)

    return render(request, 'quiz/student_quiz_reports.html', context={'my_quizes': my_quizes, 'Schedule_name': schedule_name})


from .models import TotalDegree
def student_report(request, id, schedule_name):

    my_quiz = Quiz.objects.get(id=id)

    reports = ReportResult.objects.filter(quiz=my_quiz, user=request.user)
    total = TotalDegree.objects.filter(quiz=my_quiz, user=request.user)

    return render(request, 'quiz/student_report.html', context={'reports': reports, 'total': total, 'Schedule_name': schedule_name, 'q_name': my_quiz.name})

templates/quiz/create_quiz.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="{% static 'css/form_style.css' %}">
        <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">


        <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

        <script src="{% static 'js/jquery-min.js' %}"></script>

        <script src="{% static 'js/popper.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.v5.js' %}"></script>
        <title>Add quiz</title>

        <style>
            hr{
              background-color: white;
            }
            .scroll ::-webkit-scrollbar {
              width: 2px;
              height: 1px;
            }

            .scroll ::-webkit-scrollbar-track {
              background-color: #6c757d;
            }

            .scroll ::-webkit-scrollbar-thumb {
              background-color: #6c757d;
            }

            .scroll ::-webkit-scrollbar-thumb:hover {
              background-color: #6c757d;
            }

            .bt {
              background-color: #5a6268;
              border-color: #5a6268;
            }

            .bt:hover {
              background-color: #fdfeff;
              border-color: #454b50;
            }
        </style>

    </head>
    <body class="">


        <div class="sidebar">
  <div class="logo_content">
      <div class="logo">
        <i class='bx bxl-kickstarter'></i>
          <div class="logo_name">
             anemy Lms
          </div>
          <br>

      </div>
      <i class='bx bx-menu' id="btn"></i>
  </div>
  <ul class="nav_list">

      <li>

              <a href="{% url 'instructor_home' %}">
                <i class='bx bxs-home' ></i>
                  <span class="links_name">Home</span>
              </a>
               <span class="tooltip">Home</span>
               <hr>

      </li>


      <li>
              <a href="{% url 'Schedule_home' %}">
                  <i class='bx bx-table' ></i>
                  <span class="links_name">Schedule</span>
              </a>
              <span class="tooltip">Schedule</span>
              <hr>

      </li>



  </ul>
  <div class="profile_content">
      <div class="profile">
          <div class="profile_details">
            <img src="{% static 'iconins.png' %}" alt="">
              <div class="name_job">
                  <div class="name"> {{user.first_name }} {{ user.last_name}} </div>
                  <div class="job">{{user.instructor_type}}</div>
              </div>
          </div>
          <a href="{% url 'logout-view' %}" class="text-white"><i class='bx bx-log-out' id="log_out"></i></a>
      </div>
  </div>
</div>

                <button type="button" id="mod2" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" hidden></button>
              
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Quiz Done!</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="alert alert-info d-flex align-items-center" role="alert">
                                <div>
                                    {{success}}
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-info" data-bs-dismiss="modal">Close</button>
                        </div>
                    </div>
                    </div>
                </div>

              {% if success %}

                  <script>

                    window.onload = function(){
                        document.getElementById('mod2').click();
                    }

                  </script>

                {% endif %}

        <div class="home_content">
            <header>

                  <div class="px-3 py-2 text-white" style="background-color: #11101d;">
                    <div class="container">
                      <div class="justify-content-center justify-content-lg-start">
                        <a href="#" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
                        </a>

                        <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
                            <li>
                                <a href="{% url 'instructor_home' %}" class="nav-link text-white">home</a>
                            </li>
                            <li>
                                <a href="{% url 'add-quiz' Schedule_name %}" class="nav-link text-white">Add quiz</a>
                            </li>

                            <li>
                                <a href="{% url 'my-quizes-view' Schedule_name %}" class="nav-link text-white">My quizes</a>
                            </li>

                            <li>
                                <a href="{% url 'reports-view' Schedule_name %}" class="nav-link text-white">Quiz report</a>
                            </li>


                          <li>

                            <div class="dropdown ">
                              <button class="btn dropdown-toggle nav-link text-white " type="button" id="triggerId" data-toggle="dropdown" aria-haspopup="true"
                                  aria-expanded="false">
                                  Schedule
                            </button>
                              <div class="dropdown-menu" aria-labelledby="triggerId">

                                {% for instructor_Schedule in instructor_Schedule %}
                                  <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="{% url 'Schedule_Instructor' instructor_Schedule.instructor_schedule_name %}">
                                    {{instructor_Schedule.instructor_schedule_name}}</a>
                                  <div class="dropdown-divider"></div>
                                {% endfor %}


                              </div>
                            </div>
                          </li>




                        </ul>


                    </div>
                  </div>

                <!-- <div class="px-3 py-2 border-bottom mb-3">
                  <div class="container d-flex flex-wrap justify-content-center">


                    <div class="text-end">
                      <center><b>welcome {{user.instructor_type}} : {{user.first_name }} {{ user.last_name}} </b></center>
                    </div>

                  </div>
                </div> -->

            </header>


                <div class="row justify-content-center">
                    <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12 mb-5">
                        <form action="" method="post">{% csrf_token %}
                            <div class="form_add_quiz">
                                {% for f in quiz_form %}
                                    <label class="mt-3">{{ f.label }}*</label>
                
                                    {% if f.help_text  %}
                                        <p class="text-muted">{{ f.help_text }}</p>
                                    {% endif %}
                
                                    {{ f }}
                
                                    {% if f.errors %}
                                        {% for error in f.errors %}
                                            <div class="alert alert-danger" role="alert">
                                                <strong>{{ error|escape }}</strong>
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                    
                                {% endfor %}
                            </div>
                            
                            <input class="btn btn-danger btn-sm" type="button" onclick="g_code()" value="Generate code">
                            <button type="submit" class="btn" style="background-color: #600377; color: #fff;">Save</button>
                        </form>
                    </div>
                </div>
                
                <script>

                    const g_code = () =>{
                        $.ajax({
                            url: `${window.location.origin}/quiz-conf/response_code/`,
                            success: function(response){
                                $('#id_quiz_code').val(response['code'])
                            }
                        })
                    }
                    let btn = document.querySelector('#btn')
                    let sidebar = document.querySelector('.sidebar')

                    btn.onclick = function(){
                        sidebar.classList.toggle('active')
                    }

                </script>
        </div>

    </body>
</html>

{% block content %}



{% endblock content %}

templates/quiz/edit_quiz.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="{% static 'css/form_style.css' %}">
        <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">


        <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

        <script src="{% static 'js/jquery-min.js' %}"></script>

        <script src="{% static 'js/popper.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.v5.js' %}"></script>
        <title>Add quiz</title>

        <style>
            hr{
              background-color: white;
            }
            .scroll ::-webkit-scrollbar {
              width: 2px;
              height: 1px;
            }

            .scroll ::-webkit-scrollbar-track {
              background-color: #6c757d;
            }

            .scroll ::-webkit-scrollbar-thumb {
              background-color: #6c757d;
            }

            .scroll ::-webkit-scrollbar-thumb:hover {
              background-color: #6c757d;
            }

            .bt {
              background-color: #5a6268;
              border-color: #5a6268;
            }

            .bt:hover {
              background-color: #fdfeff;
              border-color: #454b50;
            }
        </style>

	</head>

	<body>

        <div class="sidebar">
  <div class="logo_content">
      <div class="logo">
        <i class='bx bxl-kickstarter'></i>
          <div class="logo_name">
             anemy Lms
          </div>
          <br>

      </div>
      <i class='bx bx-menu' id="btn"></i>
  </div>
  <ul class="nav_list">

      <li>

              <a href="{% url 'instructor_home' %}">
                <i class='bx bxs-home' ></i>
                  <span class="links_name">Home</span>
              </a>
               <span class="tooltip">Home</span>
               <hr>

      </li>


      <li>
              <a href="{% url 'Schedule_home' %}">
                  <i class='bx bx-table' ></i>
                  <span class="links_name">Schedule</span>
              </a>
              <span class="tooltip">Schedule</span>
              <hr>

      </li>



  </ul>
  <div class="profile_content">
      <div class="profile">
          <div class="profile_details">
            <img src="{% static 'iconins.png' %}" alt="">
              <div class="name_job">
                  <div class="name"> {{user.first_name }} {{ user.last_name}} </div>
                  <div class="job">{{user.instructor_type}}</div>
              </div>
          </div>
          <a href="{% url 'logout-view' %}" class="text-white"><i class='bx bx-log-out' id="log_out"></i></a>
      </div>
  </div>
</div>



		<button type="button" id="mod2" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" hidden>
		</button>

		<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
			<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Quiz Done!</h5>
				</div>
				<div class="modal-body">
					<div class="alert alert-info d-flex align-items-center" role="alert">
						<div>
							{{success}}
						</div>
					</div>
				</div>
				<div class="modal-footer">
				<button type="button" class="btn btn-info" data-bs-dismiss="modal">Close</button>
				</div>
			</div>
			</div>
		</div>

		{% if success %}
			<script>
				window.onload = function(){
					document.getElementById('mod2').click();
					document.getElementById('id_start_quiz').value = ''

				}
			</script>

		{% elif not success %}
			<script>
				window.onload = function(){
					document.getElementById('id_start_quiz').value = ''

				}
			</script>
		{% endif %}

        <div class="home_content">

            <header>

                  <div class="px-3 py-2 text-white" style="background-color: #11101d;">
                    <div class="container">
                      <div class="justify-content-center justify-content-lg-start">
                        <a href="#" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
                        </a>

                        <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
                            <li>
                                <a href="{% url 'instructor_home' %}" class="nav-link text-white">home</a>
                            </li>
                            <li>
                                <a href="{% url 'add-quiz' Schedule_name %}" class="nav-link text-white">Add quiz</a>
                            </li>

                            <li>
                                <a href="{% url 'my-quizes-view' Schedule_name %}" class="nav-link text-white">My quizes</a>
                            </li>
                            <li>
                                <a href="{% url 'quiz-view' Schedule_name %}" class="nav-link text-white">Check view Quizes</a>
                            </li>
                            <li>
                                <a href="{% url 'reports-view' Schedule_name %}" class="nav-link text-white">Quiz report</a>
                            </li>


                          <li>

                            <div class="dropdown ">
                              <button class="btn dropdown-toggle nav-link text-white " type="button" id="triggerId" data-toggle="dropdown" aria-haspopup="true"
                                  aria-expanded="false">
                                  Schedule
                            </button>
                              <div class="dropdown-menu" aria-labelledby="triggerId">

                                {% for instructor_Schedule in instructor_Schedule %}
                                  <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="{% url 'Schedule_Instructor' instructor_Schedule.instructor_schedule_name %}">
                                    {{instructor_Schedule.instructor_schedule_name}}</a>
                                  <div class="dropdown-divider"></div>
                                {% endfor %}


                              </div>
                            </div>
                          </li>




                        </ul>


                    </div>
                  </div>
                  </div>

                <!-- <div class="px-3 py-2 border-bottom mb-3">
                  <div class="container d-flex flex-wrap justify-content-center">


                    <div class="text-end">
                      <center><b>welcome {{user.instructor_type}} : {{user.first_name }} {{ user.last_name}} </b></center>
                    </div>

                  </div>
                </div> -->

            </header>

            <div class="row justify-content-center">
		        <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12 mb-5">

					<form action="" method="post">{% csrf_token %}

						<div class="form_add_quiz">
							{% for f in quiz_form %}
								<label class="mt-3">{{ f.label }}*</label>
				
								{% if f.help_text  %}
									<p class="text-muted">{{ f.help_text }}</p>
								{% endif %}
				
								{{ f }}
				
								{% if f.errors %}
									{% for error in f.errors %}
										<div class="alert alert-danger" role="alert">
											<strong>{{ error|escape }}</strong>
										</div>
									{% endfor %}
								{% endif %}
		    
		                	{% endfor %}
						</div>
					
						<input class="btn btn-danger btn-sm" type="button" onclick="g_code()" value="Generate code">
		                <button type="submit" class="btn" style="background-color: #600377; color: #fff;">Apply</button>
		            
					</form>
		        </div>
		    </div>

        </div>

    	<script>
			
			const g_code = () =>{
	            $.ajax({
	                url: `${window.location.origin}/quiz-conf/response_code/`,
	                success: function(response){
	                    $('#id_quiz_code').val(response['code'])
	                }
	            })
	        }
	        let btn = document.querySelector('#btn')
            let sidebar = document.querySelector('.sidebar')

            btn.onclick = function(){
                sidebar.classList.toggle('active')
            }
		</script>

	</body>


</html>